import type { HeuristicEvaluation, RedesignCallout, ScreenshotAnnotation } from "./types";

const mgEmployeesRedesignCallouts: RedesignCallout[] = [
  {
    findingId: "HE-001",
    title: "No clear paths for different tasks",
    problem: "The hero bundled its main tasks into one line, so people could not tell where to start.",
    change: "Three task cards below the hero for check online, learn, and extra savings.",
    severity: "high",
  },
  {
    findingId: "HE-002",
    title: "Too much pension jargon",
    problem: "Navigation led with AVC before basics were explained.",
    change: "Nav relabelled to Learn about pensions. Plain English in body copy.",
    severity: "high",
  },
  {
    findingId: "HE-003",
    title: "Log in and Register sit too low",
    problem: "Register and Log in sat mid-nav as equal text links, not top right with clear hierarchy.",
    change: "Log in primary and Register secondary, grouped at the top right of the header.",
    severity: "high",
  },
  {
    findingId: "HE-004",
    title: "Hero subtext is hard to read",
    problem: "Light grey hero subtext on white is hard to read.",
    change: "Plain-English subtext with darker, WCAG-friendly contrast.",
    severity: "high",
  },
  {
    findingId: "HE-005",
    title: "Key answers sit inside closed panels",
    problem: "Useful answers were hidden behind collapsed accordions.",
    change: "Single-column FAQs with in-panel CTAs.",
    severity: "medium",
  },
  {
    findingId: "HE-008",
    title: "Cookie banner hides the main content",
    problem: "A large cookie banner covered about a quarter of the screen on first visit.",
    change: "Shorter copy and a slimmer bar.",
    severity: "medium",
  },
  {
    findingId: "HE-009",
    title: "Register appears in too many places",
    problem: "Register repeated in the header, mid-page, and footer.",
    change: "Log in first. One Register for online access label. Left-aligned CTAs.",
    severity: "medium",
  },
  {
    findingId: "HE-010",
    title: "Enrolment rules feel cold and formal",
    problem: "Auto-enrolment criteria appeared as formal bullets with no friendly summary.",
    change: "Opens with a plain summary before the bullet list.",
    severity: "medium",
  },
  {
    findingId: "HE-011",
    title: "Supporting information grid overwhelms at a glance",
    problem: "Twelve articles displayed at once with no way to defer the rest.",
    change: "Show six items first with Show more / Show less.",
    severity: "medium",
  },
  {
    findingId: "HE-012",
    title: "Hero image does not match the topic",
    problem: "A flexing-muscles photo filled the hero with no link to pensions.",
    change: "Swapped in a garden-growth image that reflects saving over time.",
    severity: "low",
  },
  {
    findingId: "HE-013",
    title: "Tall hero pushes actions below the fold",
    problem: "The hero image filled the first view and pushed the task cards off screen.",
    change: "Cropped the hero about 20% shorter so the task cards sit above the fold.",
    severity: "medium",
  },
];

const heroAboveFoldAnnotations: ScreenshotAnnotation[] = [
  {
    shape: "box",
    x: 37.5,
    y: 8.15,
    width: 9.5,
    height: 5.56,
    label: "No primary or secondary",
    labelPosition: "right",
  },
  {
    shape: "box",
    x: 89,
    y: 8.15,
    width: 6,
    height: 5.56,
    label: "Expected top right",
    labelPosition: "left",
    variant: "context",
  },
  {
    shape: "box",
    x: 50,
    y: 24.4,
    width: 72,
    height: 4.5,
    label: "Three goals in one line",
    labelPosition: "below",
  },
  {
    shape: "box",
    x: 50,
    y: 54,
    width: 75,
    height: 48,
    label: "No task cards",
    labelPosition: "inside",
  },
  {
    shape: "box",
    x: 50,
    y: 90.5,
    width: 98,
    height: 19,
    label: "Cookie bar blocks view",
    labelPosition: "above",
  },
];

const heroRoutingAnnotations: ScreenshotAnnotation[] = [
  {
    shape: "box",
    x: 50,
    y: 24.4,
    width: 72,
    height: 4.5,
    label: "Three goals in one line",
    labelPosition: "below",
  },
  {
    shape: "box",
    x: 50,
    y: 54,
    width: 75,
    height: 48,
    label: "No task cards",
    labelPosition: "inside",
  },
];

const heroContrastAnnotations: ScreenshotAnnotation[] = [
  {
    shape: "box",
    x: 50,
    y: 24.4,
    width: 72,
    height: 4.5,
    label: "Low contrast subtext",
    labelPosition: "below",
  },
];

const ctaHierarchyAnnotations: ScreenshotAnnotation[] = [
  {
    shape: "box",
    x: 29.5,
    y: 61.1,
    width: 9,
    height: 3.7,
    label: "Register shown first",
    labelPosition: "right",
  },
  {
    shape: "box",
    x: 40.5,
    y: 8.15,
    width: 5.5,
    height: 5.6,
    label: "Log in only in header",
    labelPosition: "below",
  },
  {
    shape: "arrow",
    x: 50,
    y: 99,
    width: 94,
    label: "Main Log in below fold",
  },
];

const contentJargonAnnotations: ScreenshotAnnotation[] = [
  {
    shape: "box",
    x: 23.5,
    y: 8.15,
    width: 6.5,
    height: 5.56,
    label: "Jargon in nav",
    labelPosition: "right",
  },
  {
    shape: "box",
    x: 50,
    y: 31,
    width: 82,
    height: 8,
    label: "Answers hidden",
    labelPosition: "below",
  },
  {
    shape: "box",
    x: 50,
    y: 54,
    width: 84,
    height: 9,
    label: "Dense warning copy",
    labelPosition: "right",
  },
  {
    shape: "box",
    x: 63.4,
    y: 84.4,
    width: 26,
    height: 25,
    label: "Register and Log in sit low",
    labelPosition: "left",
  },
];

export const mgEmployeesEvaluation: HeuristicEvaluation = {
  slug: "mg-employees",
  title: "M&G Employees heuristic evaluation",
  client: "M&G / Prudential Workplace Pensions",
  accent: "#E85D04",
  executiveSummary: {
    whatWasEvaluated:
      "The Employees page at workplacepensions.mandg.com/employees (desktop review, June 2026).",
    usabilityHealth:
      "The content is good, but people struggle to pick their next step. Jargon and weak contrast make it harder.",
    topIssues: [
      "No clear paths for checking online, learning, or extra savings",
      "Jargon before plain explanations",
      "Log in and Register sit too low on the page",
      "Hero subtext is hard to read",
    ],
    mainRisks: [
      "People leave without logging in",
      "Support calls replace self-service",
      "Low contrast hurts low-vision users",
    ],
    recommendedNextSteps: [
      "Add task cards and promote Log in",
      "Lead with plain English",
      "Fix hero contrast to WCAG AA",
      "Test task labels with five users",
    ],
  },
  scope: {
    evaluatedUrl: "https://workplacepensions.mandg.com/employees/",
    evaluationDate: "2026-06-15",
    evaluator: "Shaun Leishman (expert review)",
    userGroups: [
      "Workplace pension members",
      "New and returning online users",
    ],
    tasksEvaluated: [
      "Understand what the page offers",
      "Log in, register, or explore extra savings",
      "Find help without calling support",
    ],
    heuristicsUsed: ["Nielsen Norman Group H01–H10"],
    additionalLenses: ["Accessibility", "Content clarity", "Responsive behaviour"],
    limitations: [
      "One reviewer, desktop only. Mobile and logged-in flows were not tested.",
      "A cookie banner on first visit may change what people see first.",
    ],
  },
  severitySummary: {
    critical: 0,
    high: 4,
    medium: 7,
    low: 2,
  },
  themes: [
    {
      label: "Task routing and actions",
      findingIds: ["HE-001", "HE-003", "HE-009"],
    },
    {
      label: "Content and language",
      findingIds: ["HE-002", "HE-005", "HE-010", "HE-012"],
    },
    {
      label: "Accessibility",
      findingIds: ["HE-004", "HE-007"],
    },
    {
      label: "Page structure",
      findingIds: ["HE-006", "HE-008", "HE-011", "HE-013"],
    },
  ],
  findings: [
    {
      finding_id: "HE-001",
      title: "No clear paths for different tasks",
      screen_or_flow: "Hero",
      user_task: "Pick the next step",
      primary_heuristic: "H06",
      secondary_heuristics: ["H08"],
      additional_lenses: ["L02"],
      description:
        "The hero bundles its main tasks into one line with no task cards, so people cannot tell where to start.",
      evidence: {
        observed_where: "Hero",
        observed_behaviour:
          "One subheading bundles three goals into a single line, and there are no task cards to route people to each job.",
        expected_behaviour:
          "Clear task cards on first view, each routing to one job like checking online, learning the basics, or extra savings.",
      },
      user_impact: "Unsure users leave without acting.",
      severity: "high",
      confidence: "high",
      recommendation:
        "Add three task cards above the fold, one for each main job, so people can pick their path on first view.",
      owner: "Design",
      status: "new",
      priority: { frequency: 5, impact: 4, persistence: 5 },
      screenshot_reference: "/metrics/case-studies/mg-employees/hero-above-fold.png",
      screenshot_annotations: heroRoutingAnnotations,
    },
    {
      finding_id: "HE-002",
      title: "Too much pension jargon",
      screen_or_flow: "Body and nav",
      user_task: "Understand workplace pensions",
      primary_heuristic: "H02",
      secondary_heuristics: ["H10"],
      additional_lenses: ["L02"],
      description:
        "Technical terms appear with no plain-English help, and the nav puts AVC Schemes before the basics.",
      evidence: {
        observed_where: "Header nav and body sections",
        observed_behaviour: "AVC, IGC, and trust scheme labels have no glossary.",
        expected_behaviour: "Short plain summary first. Jargon only with a brief explanation.",
      },
      user_impact: "People with less money knowledge feel lost.",
      severity: "high",
      confidence: "high",
      recommendation: "Add a plain-English summary at the top. Explain AVC and IGC in simple terms.",
      owner: "Content",
      status: "new",
      priority: { frequency: 4, impact: 4, persistence: 4 },
      screenshot_reference: "/metrics/case-studies/mg-employees/content-jargon.png",
      screenshot_annotations: contentJargonAnnotations,
    },
    {
      finding_id: "HE-003",
      title: "Log in and Register lack hierarchy",
      screen_or_flow: "Header and CTAs across page",
      user_task: "Log in or register",
      primary_heuristic: "H08",
      secondary_heuristics: ["H06"],
      additional_lenses: ["L04"],
      description:
        "Register and Log in use the same text-link style mid-nav. Neither reads as primary or secondary, and neither sits in the usual top-right spot.",
      evidence: {
        observed_where: "Header nav and mid-page CTAs",
        observed_behaviour:
          "Register and Log in look identical in the nav. The first strong button is Register mid-page, below the cookie bar.",
        expected_behaviour:
          "Log in primary at top right, Register secondary beside it, and one clear order everywhere.",
      },
      user_impact: "Returning users hunt for Log in.",
      severity: "high",
      confidence: "high",
      recommendation:
        "Group Log in and Register at the top right. Style Log in as primary and Register as secondary.",
      owner: "Design",
      status: "new",
      priority: { frequency: 5, impact: 4, persistence: 5 },
      screenshot_reference: "/metrics/case-studies/mg-employees/cta-hierarchy.png",
      screenshot_annotations: ctaHierarchyAnnotations,
      screenshot_caption:
        "Register now is the first strong mid-page CTA. Main Log in buttons sit further down, often below the cookie bar.",
    },
    {
      finding_id: "HE-004",
      title: "Hero subtext is hard to read",
      screen_or_flow: "Hero",
      user_task: "Read the page purpose",
      primary_heuristic: "H08",
      additional_lenses: ["L01"],
      description:
        "Hero subtext uses light grey on white, so the contrast is too weak for body text.",
      evidence: {
        observed_where: "Hero below the main heading",
        observed_behaviour: "Subtext fades into the background, especially for low-vision users.",
        expected_behaviour: "Body text should meet WCAG AA contrast at 4.5 to 1.",
      },
      user_impact: "People may miss what the page is for.",
      severity: "high",
      confidence: "high",
      recommendation: "Darken the subtext and check contrast with a tool.",
      owner: "Design",
      status: "new",
      priority: { frequency: 5, impact: 3, persistence: 4 },
      accessibility_lens: {
        is_accessibility_related: true,
        wcag_principle: "WCAG Perceivable, minimum contrast",
        notes: "Likely fails WCAG 2.2 SC 1.4.3 for normal text",
      },
      screenshot_reference: "/metrics/case-studies/mg-employees/hero-contrast.png",
      screenshot_annotations: heroContrastAnnotations,
    },
    {
      finding_id: "HE-005",
      title: "Key answers sit inside closed panels",
      screen_or_flow: "FAQ accordions",
      user_task: "Find answers without calling",
      primary_heuristic: "H06",
      secondary_heuristics: ["H08"],
      additional_lenses: ["L02"],
      description:
        "FAQ topics sit behind collapsed accordions, so people open each one to hunt for an answer.",
      evidence: {
        observed_where: "Mid-page accordion grid",
        observed_behaviour: "All panels start closed.",
        expected_behaviour: "Show top questions openly. Use accordions for rare topics only.",
      },
      user_impact: "People miss useful guidance and call support.",
      severity: "medium",
      confidence: "high",
      recommendation: "Show the three most common questions as visible text or quick links.",
      owner: "Content",
      status: "new",
      priority: { frequency: 3, impact: 3, persistence: 3 },
    },
    {
      finding_id: "HE-006",
      title: "Brand names do not match",
      screen_or_flow: "Browser tab and header",
      user_task: "Confirm this is the right site",
      primary_heuristic: "H02",
      secondary_heuristics: ["H04"],
      description:
        "The URL says M&G, the tab title says Prudential, and the logo says Pru, with no line explaining how they link.",
      evidence: {
        observed_where: "Browser title and header logo",
        observed_behaviour: "Three brand names appear with no explanation.",
        expected_behaviour: "One clear brand, or one short reassurance line.",
      },
      user_impact: "Trust drops if the employer letter used a different name.",
      severity: "low",
      confidence: "medium",
      recommendation: "Match the page title to the visible brand.",
      owner: "Content",
      status: "new",
      priority: { frequency: 2, impact: 2, persistence: 2 },
    },
    {
      finding_id: "HE-007",
      title: "Screen readers hear vague link names",
      screen_or_flow: "External links",
      user_task: "Follow links with assistive tech",
      primary_heuristic: "H02",
      additional_lenses: ["L01"],
      description: "Links are read as opens in a new tab without saying where they go.",
      evidence: {
        observed_where: "Header and body links",
        observed_behaviour: "Accessible names lack destination context.",
        expected_behaviour: "Each link names its destination.",
      },
      user_impact: "Screen reader users must try links one by one.",
      severity: "medium",
      confidence: "high",
      recommendation: "Add clear link text or aria-labels with the destination name.",
      owner: "Engineering",
      status: "new",
      priority: { frequency: 2, impact: 4, persistence: 4 },
      accessibility_lens: {
        is_accessibility_related: true,
        wcag_principle: "WCAG link purpose (Operable and Understandable)",
        notes: "Likely fails WCAG 2.2 SC 2.4.4 and 2.4.9",
      },
    },
    {
      finding_id: "HE-008",
      title: "Cookie banner hides the main content",
      screen_or_flow: "Cookie banner",
      user_task: "See the page purpose on first visit",
      primary_heuristic: "H08",
      additional_lenses: ["L05"],
      description: "A large cookie banner covers about a quarter of the screen on first visit.",
      evidence: {
        observed_where: "Bottom of viewport on first visit",
        observed_behaviour: "Little actionable content shows without scrolling.",
        expected_behaviour: "Use a compact bar so purpose and actions stay visible.",
      },
      user_impact: "First-time visitors may bounce before they understand the offer.",
      severity: "medium",
      confidence: "medium",
      recommendation: "Use a slim bottom bar. Track scroll depth before and after.",
      owner: "Product",
      status: "new",
      priority: { frequency: 5, impact: 3, persistence: 1 },
    },
    {
      finding_id: "HE-009",
      title: "Register appears in too many places",
      screen_or_flow: "CTAs",
      user_task: "Register for online access",
      primary_heuristic: "H04",
      description:
        "Register shows in the header, mid-page, and footer with the same label.",
      evidence: {
        observed_where: "Header, mid-page card, footer",
        observed_behaviour: "Three Register entry points look the same.",
        expected_behaviour: "One primary Register path.",
      },
      user_impact: "Users hesitate or click the wrong link.",
      severity: "medium",
      confidence: "high",
      recommendation: "Use one main Register button labelled Register for online access.",
      owner: "Design",
      status: "new",
      priority: { frequency: 3, impact: 3, persistence: 4 },
    },
    {
      finding_id: "HE-010",
      title: "Enrolment rules feel cold and formal",
      screen_or_flow: "Workplace pensions section",
      user_task: "Know if they are enrolled",
      primary_heuristic: "H10",
      additional_lenses: ["L02"],
      description: "Enrolment criteria appear as formal bullets with no friendly summary first.",
      evidence: {
        observed_where: "Workplace pensions block",
        observed_behaviour: "Rules read like legal text.",
        expected_behaviour: "Start with a short reassuring summary, then detail.",
      },
      user_impact: "Anxious users may think they are excluded.",
      severity: "medium",
      confidence: "high",
      recommendation:
        "Lead with Most UK employees earning over £10,000 are enrolled automatically.",
      owner: "Content",
      status: "new",
      priority: { frequency: 2, impact: 3, persistence: 2 },
    },
    {
      finding_id: "HE-011",
      title: "Supporting information grid overwhelms at a glance",
      screen_or_flow: "Supporting information",
      user_task: "Find a specific guide",
      primary_heuristic: "H08",
      secondary_heuristics: ["H06"],
      additional_lenses: ["L02"],
      description: "Twelve tiles appear at once with equal visual weight.",
      evidence: {
        observed_where: "Supporting information grid",
        observed_behaviour: "All twelve articles show with no collapse option.",
        expected_behaviour: "Show six items first. Let people expand for the rest.",
      },
      user_impact: "Too much to take in near the page end.",
      severity: "medium",
      confidence: "high",
      recommendation: "Display six items by default with a Show more control.",
      owner: "Design",
      status: "new",
      priority: { frequency: 2, impact: 2, persistence: 2 },
    },
    {
      finding_id: "HE-012",
      title: "Hero image does not match the topic",
      screen_or_flow: "Hero",
      user_task: "Grasp what the page is about",
      primary_heuristic: "H02",
      secondary_heuristics: ["H08"],
      additional_lenses: ["L02"],
      description:
        "The hero image shows a flexing swimmer, which says nothing about pensions or saving.",
      evidence: {
        observed_where: "Hero banner",
        observed_behaviour:
          "A large flexing-muscles photo fills the hero but does not reflect pensions, saving, or the page content.",
        expected_behaviour:
          "A hero image that signals the topic, like growth or planning ahead, so the visual supports the message.",
      },
      user_impact: "The image adds visual noise and misses a chance to set the topic.",
      severity: "low",
      confidence: "high",
      recommendation:
        "Use an image that signals growth or long-term saving, or drop the image and keep the space clean.",
      owner: "Design",
      status: "new",
      priority: { frequency: 4, impact: 2, persistence: 2 },
    },
    {
      finding_id: "HE-013",
      title: "Tall hero image pushes the actions below the fold",
      screen_or_flow: "Hero",
      user_task: "See the main actions on first view",
      primary_heuristic: "H08",
      secondary_heuristics: ["H06"],
      additional_lenses: ["L05"],
      description:
        "A tall hero image fills the first view, so the task cards below it start off the screen.",
      evidence: {
        observed_where: "Hero and first view",
        observed_behaviour:
          "The hero image takes up most of the first screen, pushing the task cards below the fold on common laptop heights.",
        expected_behaviour:
          "A shorter hero so the main task cards sit within the first view without scrolling.",
      },
      user_impact: "People may not see the actions and assume there is nothing to do.",
      severity: "medium",
      confidence: "high",
      recommendation:
        "Crop the hero shorter so the task cards appear above the fold on a typical laptop.",
      owner: "Design",
      status: "new",
      priority: { frequency: 5, impact: 3, persistence: 4 },
    },
  ],
  actionPlan: [
    { priority: "fix_now", action: "Add task cards and clear Log in / Register order" },
    { priority: "fix_now", action: "Add a plain-English pension summary before jargon" },
    { priority: "fix_next", action: "Fix hero subtext contrast to WCAG AA" },
    { priority: "fix_next", action: "Show six supporting information items with Show more" },
    { priority: "fix_next", action: "Give external links clear accessible names" },
    { priority: "monitor", action: "Track cookie banner impact on scroll and CTA clicks" },
    { priority: "validate", action: "Run a five-user card sort on task labels" },
  ],
  screenshots: [
    {
      src: "/metrics/case-studies/mg-employees/hero-above-fold.png",
      alt: "Hero with faint subtext and no task routing",
      caption:
        "Register and Log in sit mid-nav with equal weight. Users expect Log in top right as the primary action.",
      annotations: heroAboveFoldAnnotations,
    },
    {
      src: "/metrics/case-studies/mg-employees/cta-hierarchy.png",
      alt: "Register is the first mid-page CTA, and Log in sits lower on the page",
      caption: "Register is prominent mid-page. Log in is only a small header link here.",
      annotations: ctaHierarchyAnnotations,
    },
    {
      src: "/metrics/case-studies/mg-employees/content-jargon.png",
      alt: "Jargon-heavy sections with actions at the bottom",
      caption: "The body leads with jargon. Main actions sit near the bottom.",
      annotations: contentJargonAnnotations.filter((_, index) => index === 0 || index === 3),
    },
  ],
  redesignSummary: {
    intro:
      "The mock keeps the live layout and styles, with changes focused on task routing, plain language, and clearer calls to action.",
    callouts: mgEmployeesRedesignCallouts,
    implemented: [
      "Three task cards so people can pick log in, learn, or extra savings",
      "Log in primary and Register secondary at the top right of the header",
      "Plain-English hero copy with stronger contrast",
      "Hero image that reflects growth instead of an unrelated photo",
      "Shorter hero so the task cards sit above the fold",
      "Single-column FAQ accordions with in-panel CTAs",
      "Slimmer cookie bar",
      "Manage online puts Log in before Register with left-aligned buttons",
      "Supporting information shows six items first, then Show more",
    ],
    planned: [
      "Full content pass to replace remaining jargon",
      "WCAG AA contrast check on all text and buttons",
      "Accessible names on external links",
      "Cookie banner tested for scroll and conversion",
      "Five-user card sort on task labels",
      "Mobile and tablet layout review",
    ],
  },
};

export function getEvaluationBySlug(slug: string): HeuristicEvaluation | undefined {
  if (slug === "mg-employees") return mgEmployeesEvaluation;
  return undefined;
}

export { mgEmployeesRedesignCallouts };
